version: '3'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:80"
    command: php -S 0.0.0.0:80

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: tombola
      MYSQL_USER: bingo
      MYSQL_PASSWORD: bingo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./partita.sql:/docker-entrypoint-initdb.d/partita.sql
      - ./db-data:/var/lib/mysql
    ports:
      - "8889:3306"